More Tweaking of Check_Tests.yml
* Prototyping churn

diff --git a/.github/workflows/Check_Tests.yml b/.github/workflows/Check_Tests.yml
--- a/.github/workflows/Check_Tests.yml
+++ b/.github/workflows/Check_Tests.yml
@@ -104,7 +104,7 @@ jobs:
         id: reftestfiles
         shell: bash
         run: |
-          cd cpython ;
+          cd cpython || exit 14 ;
           ls -lap . ;
           FILES=$(git ls-files --exclude-standard -- ${{ env.TEST_MATCH_PATTERN }} )
           if [ -z "$FILES" ]; then
@@ -124,6 +124,7 @@ jobs:
         shell: bash
         if: ${{ !cancelled() }}
         run: |
+          cd cpython || exit 14 ;
           if [[ -r LICENSE ]] ; then
             printf "\n\n"
             cat <LICENSE ;
@@ -131,6 +132,7 @@ jobs:
           else
             printf "%s\n" "::warning title=UNLICENSED:: This is an UNLICENSED Build"
           fi
+          cd .. ;
         # this next part is WIP and needs to be updated with filtering for more control of what parts of the referance lib is used
       - name: "Integrate Cpython Test file"
         id: merge_theirs
@@ -171,15 +173,15 @@ jobs:
             time (
               RUSTPYTHONPATH=Lib cargo run --release -- Lib/test/"${REF_FILE_NAME}" || RAW_COPY_OUTCOME='failing'
               if [[ ( -n ${RAW_COPY_OUTCOME} ) ]] ; then
-                printf "::error file='%s',title='testing-failure':: Could not copy and pass tests for file.\n" "${referance_file}" >2 ;
+                printf "::warning file='%s',title='test-warning':: Could not copy and pass tests for file.\n" "${referance_file}" ;
                 (
                   RUSTPYTHONPATH=Lib cargo run --release -- ./scripts/fix_test.py --path ./Lib/test/"${REF_FILE_NAME}" || FIX_COPY_OUTCOME='unfixed' ;
                 ) ;
-                if [[ ( -n ${RAW_COPY_OUTCOME} ) ]] ; then
-                  printf "::error file='%s',title='testing-failure':: Could not copy and auto-fix tests for file.\n" "${referance_file}" >2 ;
+                if [[ ( -n ${FIX_COPY_OUTCOME} ) ]] ; then
+                  printf "::error file='%s',title='testing-failure':: Could not copy and auto-fix tests for file.\n" "${referance_file}" >>2 ;
                   # reset broken integration to last rustpython copy
-                  git restore "${referance_file}" || : ;
-                  git checkout -- "${referance_file}" || : ;
+                  git restore --ignore-unmerged --worktree --staged "${referance_file}" || : ;
+                  git checkout -f --ignore-unmerged -- "${referance_file}" || : ;
                   # TODO: validate and set FIX_COPY_OUTCOME="reverted"
                 else
                   FIX_COPY_OUTCOME="fixed"
@@ -194,7 +196,7 @@ jobs:
               printf "FIX_COPY_%s_OUTCOME=%s\n" "${REF_FILE_NAME}" "${FIX_COPY_OUTCOME}" >> "$GITHUB_ENV" ;
               printf "RAW_COPY_%s_OUTCOME=%s\n" "${REF_FILE_NAME}" "${RAW_COPY_OUTCOME}" >> "$GITHUB_ENV" ;
               # should dump a diff or something here
-              printf "\n\n"
+              printf "\n\n" ;
             ) ;
             wait ;
             # cleanup temp env
