Smarter filtering for direct invocation in Check_Tests.yml
* With a minimal working PoC for automation of using `scripts/fix_test.py` this has reached the very first milestone of a single working test
* Still experimental WIP
* see RustPython/RustPython#5974 for context

diff --git a/.github/workflows/Check_Tests.yml b/.github/workflows/Check_Tests.yml
--- a/.github/workflows/Check_Tests.yml
+++ b/.github/workflows/Check_Tests.yml
@@ -8,6 +8,10 @@ run-name: Prototyping integration tests ${{ github.ref_name }}
 #
 # Required Secrets:
 # NONE
+#
+# WORK IN PROGRESS
+# search for "TODO" in file for more details on what is still un-implemented
+
 
 on:  # yamllint disable-line rule:truthy
   push:
@@ -66,7 +70,7 @@ jobs:
       bootstrap_status: ${{ steps.smoke_testing.outcome }}
     env:
       PYTHON_VERSION: ${{ matrix.python-version }}
-      
+    # TODO: move to seperate action
     steps:
       - name: Checkout RustPython repository
         id: rpython
@@ -162,48 +166,57 @@ jobs:
         run: |
           cd rustpython || exit 13 ;
           for referance_file in ${{ steps.reftestfiles.outputs.files }} ; do
-            # TODO: RustPython workaround Windows timeout for hangs
-            printf "Now Testing '%s'\n" "${referance_file}"
-            # vars for subshell but not for workflow
-            export REF_FILE_NAME=$(basename "${referance_file}") ;
-            printf "\n::group::%s\n" "${REF_FILE_NAME}" ;
-            # TODO: test with cpython first
-            # TODO: add to list of files that need additional prep due to hanging or unexpected failures that need to be removed
-            # Execute the testing command in a subshell
-            time (
-              RUSTPYTHONPATH=Lib cargo run --release -- Lib/test/"${REF_FILE_NAME}" || RAW_COPY_OUTCOME='failing'
-              if [[ ( -n ${RAW_COPY_OUTCOME} ) ]] ; then
-                printf "::warning file='%s',title='test-warning':: Could not copy and pass tests for file.\n" "${referance_file}" ;
-                (
-                  RUSTPYTHONPATH=Lib cargo run --release -- ./scripts/fix_test.py --path ./Lib/test/"${REF_FILE_NAME}" || FIX_COPY_OUTCOME='unfixed' ;
+            if [[ ( -f "${referance_file}" ) ]] ; then
+              # See https://devguide.python.org/testing/run-write-tests
+              # Heuristic: "if some module does not have unittest.main(), then most likely it does not support direct invocation."
+              if grep -qF "unittest.main()" "${referance_file}" 2>dev/null ; then
+                # TODO: RustPython workaround Windows timeout for hangs
+                printf "Now Testing '%s'\n" "${referance_file}"
+                # vars for subshell but not for workflow
+                export REF_FILE_NAME=$(basename "${referance_file}") ;
+                printf "\n::group::%s\n" "${REF_FILE_NAME}" ;
+                # TODO: test with cpython first for baseline
+                # TODO: add to list of files that need additional prep due to hanging or unexpected failures that need to be removed
+                # Execute the testing command in a subshell
+                time (
+                  RUSTPYTHONPATH=Lib cargo run --release -- Lib/test/"${REF_FILE_NAME}" || RAW_COPY_OUTCOME='failing'
+                  if [[ ( -n ${RAW_COPY_OUTCOME} ) ]] ; then
+                    printf "::warning file='%s',title='test-warning':: Could not copy and pass tests for file.\n" "${referance_file}" ;
+                    (
+                      RUSTPYTHONPATH=Lib cargo run --release -- ./scripts/fix_test.py --path ./Lib/test/"${REF_FILE_NAME}" || FIX_COPY_OUTCOME='unfixed' ;
+                    ) ;
+                    if [[ ( -n ${FIX_COPY_OUTCOME} ) ]] ; then
+                      printf "::error file='%s',title='testing-failure':: Could not copy and auto-fix tests for file.\n" "${referance_file}" >>2 ;
+                      # reset broken integration to last rustpython copy
+                      git restore --ignore-unmerged --worktree --staged "${referance_file}" || : ;
+                      git checkout -f --ignore-unmerged -- "${referance_file}" || : ;
+                      # TODO: validate and set FIX_COPY_OUTCOME="reverted"
+                    else
+                      FIX_COPY_OUTCOME="fixed"
+                      RAW_COPY_OUTCOME="incompatable"
+                    fi ;
+                  else
+                    FIX_COPY_OUTCOME="skipped"
+                    RAW_COPY_OUTCOME="compatable"
+                  fi ;
+                  printf "\n---\n%s Outcome:\n\tDirectly:%s\n\tAuto-Fix:%s\n\n" "${REF_FILE_NAME}" "${RAW_COPY_OUTCOME}" "${FIX_COPY_OUTCOME}" ;
+                  wait ; # used to force boundry for std out read/write race in UI 
+                  printf "FIX_COPY_%s_OUTCOME=%s\n" "${REF_FILE_NAME}" "${FIX_COPY_OUTCOME}" >> "$GITHUB_ENV" ;
+                  printf "RAW_COPY_%s_OUTCOME=%s\n" "${REF_FILE_NAME}" "${RAW_COPY_OUTCOME}" >> "$GITHUB_ENV" ;
+                  # should dump a diff or something here
+                  printf "\n\n" ;
                 ) ;
-                if [[ ( -n ${FIX_COPY_OUTCOME} ) ]] ; then
-                  printf "::error file='%s',title='testing-failure':: Could not copy and auto-fix tests for file.\n" "${referance_file}" >>2 ;
-                  # reset broken integration to last rustpython copy
-                  git restore --ignore-unmerged --worktree --staged "${referance_file}" || : ;
-                  git checkout -f --ignore-unmerged -- "${referance_file}" || : ;
-                  # TODO: validate and set FIX_COPY_OUTCOME="reverted"
-                else
-                  FIX_COPY_OUTCOME="fixed"
-                  RAW_COPY_OUTCOME="incompatable"
-                fi ;
+                wait ;
+                # cleanup temp env
+                unset FIX_COPY_OUTCOME 2>/dev/null || : ;
+                unset RAW_COPY_OUTCOME 2>/dev/null || : ;
+                unset REF_FILE_NAME 2>/dev/null || : ;
+                printf "\n::endgroup::\n" ;
               else
-                FIX_COPY_OUTCOME="skipped"
-                RAW_COPY_OUTCOME="compatable"
-              fi ;
-              printf "\n---\n%s Outcome:\n\tDirectly:%s\n\tAuto-Fix:%s\n\n" "${REF_FILE_NAME}" "${RAW_COPY_OUTCOME}" "${FIX_COPY_OUTCOME}" ;
-              wait ; # used to force boundry for std out read/write race in UI 
-              printf "FIX_COPY_%s_OUTCOME=%s\n" "${REF_FILE_NAME}" "${FIX_COPY_OUTCOME}" >> "$GITHUB_ENV" ;
-              printf "RAW_COPY_%s_OUTCOME=%s\n" "${REF_FILE_NAME}" "${RAW_COPY_OUTCOME}" >> "$GITHUB_ENV" ;
-              # should dump a diff or something here
-              printf "\n\n" ;
-            ) ;
-            wait ;
-            # cleanup temp env
-            unset FIX_COPY_OUTCOME 2>/dev/null || : ;
-            unset RAW_COPY_OUTCOME 2>/dev/null || : ;
-            unset REF_FILE_NAME 2>/dev/null || : ;
-            printf "\n::endgroup::\n" ;
+                # TODO: else can not be run directly and needs to be invoked with -m unittest -v test.
+                printf "\nNow Skipping '%s'\n\n" "${referance_file}" ;
+              fi ; # TODO: else can not be run directly and needs to be invoked with -m unittest -v test.
+            fi ;
           done
           cd .. ;
       - name: Post-Clean
