DEBUG Check_Tests.yml builds
disabled multi-os to test builds in separate step

diff --git a/.github/workflows/Check_Tests.yml b/.github/workflows/Check_Tests.yml
--- a/.github/workflows/Check_Tests.yml
+++ b/.github/workflows/Check_Tests.yml
@@ -44,7 +44,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-latest, macos-14, macos-15, windows-latest]
+        os: [ubuntu-latest]  # disabled , macos-14, macos-15, windows-latest]
         python-version: ["${{ vars.PYTHON_OLD_MIN }}", "${{ vars.PYTHON_OLD_EXTRA }}", "${{ vars.PYTHON_DEFAULT }}", "${{ vars.PYTHON_EXPERIMENTAL }}"]
         experimental: [true]
         include:
@@ -114,6 +114,18 @@ jobs:
             printf "::warning, file='%s',title='integration disabled':: SKIPPING integration of file.\n" "${referance_file}" ;
             #cp -vf cpython/"${referance_file}" rustpython/"${referance_file}" || printf "::warning, file='%s',title='integration failure':: Could not integrate file.\n" "${referance_file}" ;
           done
+      - name: Pre-Test Build check
+        id: build_testing
+        shell: bash
+        if: ${{ !cancelled() }}
+        run: |
+          cd rustpython || exit 13 ;
+            printf "Now Building '%s'\n" ""
+            # Execute the testing command in a subshell
+            (
+              RUSTPYTHONPATH=Lib cargo run --release --version || printf "::error, title='build failure':: Could not pass build step for version check.\n" ;
+            ) ;
+          cd .. ;
       - id: output_python
         name: "bootstrap Python"
         shell: bash
